import Link from "next/link";
import { CodeBlock } from "@/components/docs/code-block";

export default function ComposePage() {
  return (
    <div>
      <h1>Composition</h1>
      <p className="lead">
        Build AGENTS.md from multiple fragment files. Useful for monorepos where each package contributes instructions.
      </p>

      <h2>Fragment Patterns</h2>
      <p>AgentMD discovers fragments matching:</p>
      <ul>
        <li><code>**/agents-md/**/*.md</code> — Files in agents-md directories</li>
        <li><code>**/*.agents.md</code> — Suffixed markdown files</li>
      </ul>

      <h2>Directives</h2>
      <p>Use <code>{"<!-- agents-md: key=value -->"}</code> in fragments:</p>
      <table className="w-full text-sm">
        <thead>
          <tr>
            <th>Directive</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><code>target=nearest</code></td>
            <td>Compose into AGENTS.md in the fragment&apos;s directory (default)</td>
          </tr>
          <tr>
            <td><code>target=root</code></td>
            <td>Compose into root AGENTS.md</td>
          </tr>
          <tr>
            <td><code>target=path</code></td>
            <td>Compose into a specific path</td>
          </tr>
          <tr>
            <td><code>priority=N</code></td>
            <td>Ordering (higher = earlier in output)</td>
          </tr>
        </tbody>
      </table>

      <h2>Example Structure</h2>
      <CodeBlock>{`repo/
├── agents-md/
│   ├── build.agents.md      # target=root, priority=10
│   └── testing.agents.md   # target=root, priority=5
├── packages/
│   └── core/
│       └── agents-md/
│           └── core.agents.md  # target=nearest
└── AGENTS.md               # Generated`}</CodeBlock>

      <h2>CLI</h2>
      <CodeBlock>{`agentmd compose .
# Composed 2 AGENTS.md file(s)`}</CodeBlock>

      <p>Generated files include source annotations:</p>
      <CodeBlock>{`<!-- Generated by AgentMD compose. Do not edit directly. -->
<!-- source: agents-md/build.agents.md -->
## Build
...
<!-- /source: agents-md/build.agents.md -->`}</CodeBlock>

      <p className="mt-8">
        <Link href="/docs/cli" className="text-primary hover:underline">
          → CLI Reference
        </Link>
      </p>
    </div>
  );
}
