export type ProjectType = 'node' | 'python' | 'rust' | 'go' | 'nextjs' | 'react' | 'vue' | 'svelte' | 'astro' | 'fastapi' | 'express' | 'nestjs' | 'remix' | 'nuxt' | 'django' | 'rails' | 'monorepo' | 'generic';

export const TEMPLATES: Record<ProjectType, string> = {
  nextjs: `---\nagent:\n  name: nextjs-agent\n  purpose: "Work on Next.js projects"\n  guardrails:\n    - "Run tests before committing"\n---\n\n# Next.js Project\n\n## Setup\n\`\`\`bash\npnpm install\n\`\`\`\n\n## Build\n\`\`\`bash\npnpm run build\n\`\`\`\n\n## Test\n\`\`\`bash\npnpm test\n\`\`\`\n\n## Lint\n\`\`\`bash\npnpm run lint\n\`\`\`\n`,
  node: `---\n# Agent instructions for Node.js\n---\n\n## Install\n\n\`\`\`bash\npnpm install\n\`\`\`\n\n## Build\n\n\`\`\`bash\npnpm run build\n\`\`\`\n\n## Test\n\n\`\`\`bash\npnpm run test\n\`\`\`\n\n## Lint\n\n\`\`\`bash\npnpm run lint\n\`\`\`\n`,
  django: `---\nagent:\n  name: django-agent\n  purpose: "Work on Django projects"\n  guardrails:\n    - "Run tests before committing"\n    - "Never run migrate without explicit approval"\n---\n\n# Django Project\n\n## Setup\n\`\`\`bash\nuv sync\n\`\`\`\n\n## Test\n\`\`\`bash\npython manage.py test\n\`\`\`\n\n## Lint\n\`\`\`bash\nruff check .\nruff format .\n\`\`\`\n`,
  python: `---\n# Agent instructions for Python\n---\n\n## Setup\n\n\`\`\`bash\nuv sync\n\`\`\`\n\n## Test\n\n\`\`\`bash\nuv run pytest\n\`\`\`\n\n## Lint\n\n\`\`\`bash\nuv run ruff check .\n\`\`\`\n\n## Format\n\n\`\`\`bash\nuv run ruff format .\n\`\`\`\n`,
  rust: `---\n# Agent instructions for Rust\n---\n\n## Build\n\n\`\`\`bash\ncargo build\n\`\`\`\n\n## Test\n\n\`\`\`bash\ncargo test\n\`\`\`\n\n## Lint\n\n\`\`\`bash\ncargo clippy\n\`\`\`\n\n## Format\n\n\`\`\`bash\ncargo fmt\n\`\`\`\n`,
  rails: `---\nagent:\n  name: rails-agent\n  purpose: "Work on Ruby on Rails projects"\n  guardrails:\n    - "Run tests before committing"\n---\n\n# Rails Project\n\n## Setup\n\`\`\`bash\nbundle install\n\`\`\`\n\n## Test\n\`\`\`bash\nbundle exec rspec\n\`\`\`\n\n## Lint\n\`\`\`bash\nbundle exec rubocop\n\`\`\`\n`,
  go: `---\n# Agent instructions for Go\n---\n\n## Build\n\n\`\`\`bash\ngo build ./...\n\`\`\`\n\n## Test\n\n\`\`\`bash\ngo test ./...\n\`\`\`\n\n## Lint\n\n\`\`\`bash\ngolangci-lint run\n\`\`\`\n`,
  monorepo: `---\nagent:\n  name: monorepo-agent\n  purpose: "Work on pnpm monorepo projects"\n  guardrails:\n    - "Run tests from repo root"\n---\n\n# Monorepo\n\n## Setup\n\`\`\`bash\npnpm install\n\`\`\`\n\n## Build\n\`\`\`bash\npnpm run build\n\`\`\`\n\n## Test\n\`\`\`bash\npnpm run test\n\`\`\`\n\n## Lint\n\`\`\`bash\npnpm run lint\n\`\`\`\n`,
  react: `---\nagent:\n  name: react-agent\n  purpose: "Work on React projects"\n  guardrails:\n    - "Run tests before committing"\n---\n\n# React Project\n\n## Setup\n\`\`\`bash\nnpm install\n\`\`\`\n\n## Start\n\`\`\`bash\nnpm start\n\`\`\`\n\n## Test\n\`\`\`bash\nnpm test\n\`\`\`\n\n## Build\n\`\`\`bash\nnpm run build\n\`\`\`\n`,
  vue: `---\nagent:\n  name: vue-agent\n  purpose: "Work on Vue.js projects"\n  guardrails:\n    - "Run tests before committing"\n---\n\n# Vue.js Project\n\n## Setup\n\`\`\`bash\nnpm install\n\`\`\`\n\n## Dev\n\`\`\`bash\nnpm run dev\n\`\`\`\n\n## Test\n\`\`\`bash\nnpm run test\n\`\`\`\n\n## Build\n\`\`\`bash\nnpm run build\n\`\`\`\n`,
  svelte: `---\nagent:\n  name: svelte-agent\n  purpose: "Work on Svelte projects"\n  guardrails:\n    - "Run tests before committing"\n---\n\n# Svelte Project\n\n## Setup\n\`\`\`bash\nnpm install\n\`\`\`\n\n## Dev\n\`\`\`bash\nnpm run dev\n\`\`\`\n\n## Test\n\`\`\`bash\nnpm run test\n\`\`\`\n\n## Build\n\`\`\`bash\nnpm run build\n\`\`\`\n`,
  astro: `---\nagent:\n  name: astro-agent\n  purpose: "Work on Astro projects"\n  guardrails:\n    - "Run tests before committing"\n---\n\n# Astro Project\n\n## Setup\n\`\`\`bash\nnpm install\n\`\`\`\n\n## Dev\n\`\`\`bash\nnpm run dev\n\`\`\`\n\n## Test\n\`\`\`bash\nnpm run test\n\`\`\`\n\n## Build\n\`\`\`bash\nnpm run build\n\`\`\`\n`,
  fastapi: `---\nagent:\n  name: fastapi-agent\n  purpose: "Work on FastAPI projects"\n  guardrails:\n    - "Run tests before committing"\n---\n\n# FastAPI Project\n\n## Setup\n\`\`\`bash\npip install -r requirements.txt\n\`\`\`\n\n## Run\n\`\`\`bash\nuvicorn main:app --reload\n\`\`\`\n\n## Test\n\`\`\`bash\npytest\n\`\`\`\n`,
  express: `---\nagent:\n  name: express-agent\n  purpose: "Work on Express.js projects"\n  guardrails:\n    - "Run tests before committing"\n---\n\n# Express.js Project\n\n## Setup\n\`\`\`bash\nnpm install\n\`\`\`\n\n## Start\n\`\`\`bash\nnpm start\n\`\`\`\n\n## Test\n\`\`\`bash\nnpm test\n\`\`\`\n`,
  nestjs: `---\nagent:\n  name: nestjs-agent\n  purpose: "Work on NestJS projects"\n  guardrails:\n    - "Run tests before committing"\n---\n\n# NestJS Project\n\n## Setup\n\`\`\`bash\nnpm install\n\`\`\`\n\n## Development\n\`\`\`bash\nnpm run start:dev\n\`\`\`\n\n## Test\n\`\`\`bash\nnpm run test\n\`\`\`\n\n## Build\n\`\`\`bash\nnpm run build\n\`\`\`\n`,
  remix: `---\nagent:\n  name: remix-agent\n  purpose: "Work on Remix projects"\n  guardrails:\n    - "Run tests before committing"\n---\n\n# Remix Project\n\n## Setup\n\`\`\`bash\nnpm install\n\`\`\`\n\n## Dev\n\`\`\`bash\nnpm run dev\n\`\`\`\n\n## Test\n\`\`\`bash\nnpm test\n\`\`\`\n\n## Build\n\`\`\`bash\nnpm run build\n\`\`\`\n`,
  nuxt: `---\nagent:\n  name: nuxt-agent\n  purpose: "Work on Nuxt.js projects"\n  guardrails:\n    - "Run tests before committing"\n---\n\n# Nuxt.js Project\n\n## Setup\n\`\`\`bash\nnpm install\n\`\`\`\n\n## Dev\n\`\`\`bash\nnpm run dev\n\`\`\`\n\n## Test\n\`\`\`bash\nnpm test\n\`\`\`\n\n## Build\n\`\`\`bash\nnpm run build\n\`\`\`\n`,
  generic: `---\nagent:\n  name: generic-agent\n  purpose: "General purpose agent for any project"\n  guardrails:\n    - "Always validate before committing"\n---\n\n# Generic Project\n\n## Setup\n\`\`\`bash\n# Add setup commands here\n\`\`\`\n\n## Test\n\`\`\`bash\n# Add test commands here\n\`\`\`\n\n## Build\n\`\`\`bash\n# Add build commands here\n\`\`\`\n`
};
